# Site settings
title: ml blog | machine learning
email: knvinh_gmail_com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vinhkhuc.github.io" # the base hostname & protocol for your site
twitter_username: knvinh
github_username: vinhkhuc

# Build settings
markdown: kramdown

highlighter: rouge

gems:
  - jekyll-gist
  - pygments.rb
